三层架构+mvc+easyui/CMS.WebApp/Controllers/AdminNewListController.cs
using CMS.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebApp.Controllers
{
    public class AdminNewListController : Controller
    {
        //
        // GET: /AdminNewListController/
        BLL.NewsBll newsBll = new BLL.NewsBll();
        public ActionResult Index()
        {
            int pageIndex = Request["pageIndex"] != null ? int.Parse(Request["pageIndex"]) : 1;
            int pageSize = 3;
            int pageCount = newsBll.GetPageCount(pageSize);
            pageIndex = pageIndex < 1 ? 1 : pageIndex;
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;
            List<News> list = newsBll.GetPageList(pageIndex, pageSize);
            ViewData["list"] = list;
            ViewData["pageIndex"] = pageIndex;
            ViewData["pageCount"] = pageCount;
            return View();
        }

        public ActionResult GetNewInfoModel()
        {
            int id = int.Parse(Request["id"]);
            News news = newsBll.GetModel(id);//获取详细信息
            return Json(news, JsonRequestBehavior.AllowGet);
        }


        public ActionResult DeleteNewInfo()
        {
            int id = int.Parse(Request["id"]);
            if (newsBll.DeleteInfo(id))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }

        public ActionResult ShowAddInfo()
        {
            return View();
        }

        public ActionResult FileUpload()
        {
            HttpPostedFileBase postFile = Request.Files["fileUp"];//接收文件数据
            if (postFile==null)
            {
                return Content("no:请选择上传文件");
            }
            else
            {
                string fileName = Path.GetFileName(postFile.FileName); //文件名
                string fileExt = Path.GetExtension(fileName);//文件的扩展名称
                if (fileExt == ".jpg" || fileExt == ".png")
                {
                    string dir = "/ImagePath/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";
                     Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));//创建文件夹
                     string newfileName = Guid.NewGuid().ToString();//新的文件名
                     string fullDir = dir + newfileName + fileExt;//完整的路径
                     postFile.SaveAs(Request.MapPath(fullDir));//保存文件
                     return Content("ok:" + fullDir);
                }
                else
                {
                    return Content("no:文件格式错误");
                }
            }
        }
        [ValidateInput(false)]
        public ActionResult AddNewInfo(News news)
        {
            news.SubDateTime = DateTime.Now;
            if (newsBll.AddNew(news))
            {
                return Content("ok");
            }else
            {
                return Content("no");
            }
        }
    }
}

三层架构+mvc+easyui/CMS.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebApp.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

三层架构+mvc+easyui/CMS.WebApp/Controllers/LoginController.cs
using CMS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebApp.Controllers
{
    public class LoginController : Controller
    {
        //约定大于配置
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserLogin()
        {
            string vCode = Session["vCode"] == null ? string.Empty : Session["vCode"].ToString();
            if (string.IsNullOrEmpty(vCode))
            {
                return Content("null:验证码为空");
            }
            if (vCode.Equals(Request["txtCode"],StringComparison.InvariantCultureIgnoreCase))
            {
                string txtName = Request["txtName"];
                string txtPwd = Request["txtPwd"];
                BLL.UserInfoBll userInfoBll = new BLL.UserInfoBll();
                UserInfo userInfo = userInfoBll.GetUserInfo(txtName, txtPwd);
                if (userInfo != null)
                {
                    Session["UserInfo"] = userInfo;
                    Session["vCode"] = null;
                    return Content("ok:登录成功");
                }
                else
                {
                    return Content("no:登录失败");
                }
            }
            else
            {
                return Content("null:验证码错误");
            }
        }

        public ActionResult ShowValidateCode()
        {
            Common.ValidateCode validateCode = new Common.ValidateCode();
            string code = validateCode.GetRandomString(5);//获取验证码
            Session["vCode"] = code;
            byte[] buffer = validateCode.CreateValidateGraphic(code);
            return File(buffer, "image/jpeg");
        }

        public ActionResult CheckCode()
        {
            if (!string.IsNullOrEmpty(Request["txtCode"]))
            {
                if (Session["vCode"].ToString().Equals(Request["txtCode"],StringComparison.InvariantCultureIgnoreCase))
                {
                    return Content("ok");
                }
                else
                {
                    return Content("no");
                }
            }
            else
            {
                return Content("null");
            }
        }
    }
}

三层架构+mvc+easyui/CMS.WebApp/Views/AdminNewList/Index.cshtml
@using CMS.Model;
@using CMS.Common;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <link href="~/Content/pageBar.css" rel="stylesheet" />
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#divAdd").css("display", "none");
            $(".details").click(function () {
                showDetail($(this).attr("ids"));//显示详细信息
            });
            $(".deletes").click(function () {
                deleteInfo($(this).attr("ids"), $(this));//删除新闻记录
            });
            $("#addInfo").click(function () {
                addNewInfo();
            });
        });

        //添加新闻信息
        function addNewInfo() {
            $("#AddFrame").attr("src", "/AdminNewList/ShowAddInfo");
            $("#divAdd").css("display", "block");
            $('#divAdd').dialog('open');
        }

        //删除新闻
        function deleteInfo(id, control) {
            $.messager.confirm("提示", "确认是否要删除？", function (r) {
                if (r) {//成立表示删除该记录
                    //发送异步请求
                    $.ajax({
                        url: "/AdminNewList/DeleteNewInfo",
                        type: "post",
                        data: { "id": id },
                        success: function (data) {
                            if (data == "ok") {
                                $(control).parent().parent().remove();
                                $.messager.show({
                                    title: '提示',
                                    msg: '删除成功！',
                                    showType: 'show'
                                });
                            } else {
                                $.messager.tip({
                                    msg: '删除失败！',
                                    icon: 'error'
                                });
                            }
                        }
                    });

                }
            });
        }

        //显示详细信息
        function showDetail(id) {
            $.ajax({
                url: "/AdminNewList/GetNewInfoModel",
                type: "post",
                data: { "id": id },
                success: function (data) {
                    $("#title").text(data.Title);
                    $("#author").text(data.Author);
                    $("#subDateTime").text(ChangeDateFormat(data.SubDateTime));
                    $("#msg").html(data.Msg);
                }
            });
            $('#detailDiv').dialog('open');
        }

        //将序列化成json格式后日期（毫秒数）转成日期格式
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }

        //添加完成以后调用该方法关闭添加窗口
        function afterAdd() {
            $("#divAdd").dialog('close');
        }
    </script>
</head>
<body>
    <div>
        <a href="javascript:void(0)" id="addInfo">添加</a>
        @if (ViewData["list"] != null)
        {
            <table width="100%">
                <tr><th>编号</th><th>标题</th><th>作者</th><th>时间</th><th>详细</th><th>删除</th><th>修改</th></tr>
                @foreach (News news in (List<News>)ViewData["list"])
                {
                    <tr>
                        <td>@news.Id</td>
                        <td>@news.Title</td>
                        <td>@news.Author</td>
                        <td>@news.SubDateTime</td>
                        <td><a href="javascript:void(0)" class="details" ids="@news.Id">详细</a></td>
                        <td><a href="javascript:void(0)" class="deletes" ids="@news.Id">删除</a></td>
                        <td>修改</td>
                    </tr>
                }
            </table>
            <center>
                <p class="pagination">
                    @MvcHtmlString.Create(PageBar.GetPageBar((int)ViewData["pageIndex"], (int)ViewData["pageCount"]))
                    @*@Html.Raw()*@
                </p>
            </center>
        }
        else
        {
            <span>暂无数据</span>
        }

    </div>


    <!--显示详细信息-->
    <div id="detailDiv" class="easyui-dialog" title="添加新闻" style="width:800px;height:auto;display:none;" data-options="modal: true,shadow:false,resizable: true,maximizable: true,collapsible: true,closed:true,closable:true,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        alert('ok');
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#detailDiv').dialog('close');
                    }
                }]">
        <table>
            <tr><th>标题</th><td><span id="title"></span></td></tr>
            <tr><th>作者</th><td><span id="author"></span></td></tr>
            <tr><th>时间</th><td><span id="subDateTime"></span></td></tr>
            <tr><th>内容</th><td><span id="msg"></span></td></tr>
        </table>
    </div>
    <!--显示详细信息-->
    <!--添加信息内容-->

    <div id="divAdd" class="easyui-dialog" title="添加新闻" style="width:800px;height:500px;overflow:hidden" data-options="modal: true,shadow:false,resizable: true,maximizable: true,collapsible: true,closed:true,closable:true,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {//调用子窗体中的方法
                         var childWindow = $('#addframe')[0].contentwindow; //获取子窗体的window对象
                        childWindow.subForm();
                        }
                        }, {
                        text: '取消',
                        handler: function () {
                        $('#divAdd').dialog('close');
                        }
                        }]">
        <iframe id="AddFrame" scrolling="auto" width="100%" height="100%" frameborder="0" src=""></iframe>
    </div>

    <!--添加信息内容-->
</body>
</html>

三层架构+mvc+easyui/CMS.WebApp/Views/AdminNewList/ShowAddInfo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/kindeditor/themes/default/default.css" rel="stylesheet" />
    <link href="~/kindeditor/plugins/code/prettify.css" rel="stylesheet" />
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script src="~/kindeditor/kindeditor-all-min.js"></script>
    <script src="~/kindeditor/lang/zh-CN.js"></script>
    <script src="~/kindeditor/plugins/code/prettify.js"></script>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <title>添加新闻</title>
    <script type="text/javascript">
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '../plugins/code/prettify.css',
                uploadJson: '../asp.net/upload_json.ashx',
                fileManagerJson: '../asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterCreate: function () {
                    var self = this;
                    K.ctrl(document, 13, function () {
                        self.sync();
                        K('form[name=example]')[0].submit();
                    });
                    K.ctrl(self.edit.doc, 13, function () {
                        self.sync();
                        K('form[name=example]')[0].submit();
                    });
                }
            });
            prettyPrint();
        });
        $(function () {
            fileUpload();
        });

        function fileUpload() {
            $("#btnFileUp").click(function () {
                if ($("#fileUpImage").val() == "") {
                    $.messager.alert("提示", "请选择上传的图片文件", "info");
                    return;
                }
                $("#form1").ajaxSubmit({
                    type: "post",
                    url: "/AdminNewList/FileUpload",
                    success: function (data) {
                        var serverDate = data.split(':');
                        if (serverDate[0] == "ok") {
                            $("#hidImagePath").val(serverDate[1]);//将路径赋值给了隐藏域，提交表单时将提交到服务端保存到数据库
                            $("#showImage").append("<img src='" + serverDate[1] + "' width='40px' height='40px'/>");
                        } else {
                            $.messager.alert("提示",serverData[1],"info");
                        }
                    }
                });
            });
        }
        //提交表单
        function subForm() {
            $("#form1").submit();
        }
        function afterAdd() {
            window.parent.afterAdd();
        }
    </script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm("FileUpload", "AdminNewList", new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id="form1" }))
        {
            <table width="100%" height="100%">
                <tr><th>新闻名称</th><td><input type="text" name="Title" /></td></tr>
                <tr><th>作者</th><td><input type="text" name="Author" /></td></tr>
                <tr>
                    <th>上传图片</th>
                    <td>
                        <input type="file" name="fileUp" id="fileUpImage" />
                        <input type="submit" value="上传图片" id="btnFileUp"/>
                        <input type="hidden" id="hidImagePath" name="ImagePath" />
                        <div id="showImage"></div>
                    </td>
                </tr>
                <tr>
                    <th>新闻内容</th>
                    <td>
                        <textarea id="MsgContent" name="Msg" cols="100" rows="8" style="width:700px;height:200px;visibility:hidden;"></textarea>
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>

三层架构+mvc+easyui/CMS.WebApp/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">
        $(function () {
            bindClickEvent();
        });
        function bindClickEvent() {
            //绑定超连接的单击事件
            $(".detailLink").click(function () {
                var title = $(this).text();
                var url = $(this).attr("url");
                var isExt = $("#tt").tabs('exists', title);//判断页签是否存在
                if (isExt) {
                    $("#tt").tabs('select', title);
                    return;
                }
                $('#tt').tabs('add', {
                    title: title,
                    content: showContent(url),
                    closable: true
                });
            });
        }
        function showContent(url) {
            var strHtml = '<iframe src="' + url + '" scrolling="no" width="100%" height="auto" frameborder="0"></iframe>';
            return strHtml;
        }
    </script>
</head>
<body class="easyui-layout">
    <!--顶部-->
    <div data-options="region:'north',border:false" style="height:105px;background:linear-gradient(0deg, rgba(255,255,255,1) 0%, rgba(238,249,254,1) 25%, rgba(196,223,238,1) 50%, rgba(96,175,218,1) 75%, rgba(26,163,236,1) 100%);padding-left:10px;overflow:hidden;">
        <img src="/Content/Images/logo.png" height="105" />
    </div>
    <!--顶部-->
    <!--左侧-->
    <div data-options="region:'west',split:true,title:'管理栏'" style="width:200px;padding:2px;">
        <div class="easyui-accordion" data-options="multiple:true" style="width:auto;">
            <div title="新闻管理" data-options="iconCls:'icon-ok'" style="overflow:auto;padding:10px;">
                <a href="javascript:void(0)" class="detailLink" url="/AdminNewList/Index">新闻管理</a>
            </div>
            <div title="评论管理" data-options="iconCls:'icon-reload'" style="padding:10px;">
                <a href="javascript:void(0)" class="detailLink" url="/AdminCommentList/Index">评论管理</a>
            </div>
        </div>
    </div>
    <!--左侧-->
    <!--底部-->
    <div data-options="region:'south',border:false" style="height:auto;background:#A9FACD;padding:10px;text-align:center;">
        Copyright © 2023 News - 琼ICP备2021004479号-1
    </div>
    <!--底部-->

    <div data-options="region:'center',title:'内容'">
        
        <div id="tt" class="easyui-tabs" fit="true">
            <div title="新闻管理" data-options="closable:true">
                <iframe src="/AdminNewList/Index" scrolling="no" width="100%" height="99%" frameborder="0"></iframe>
            </div>
        </div>


    </div>
</body>
</html>

三层架构+mvc+easyui/CMS.WebApp/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        span{
            color :red;
        }
    </style>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("btnLogin").style.display = "none";

            let txtName = document.getElementById("txtName");
            txtName.onblur = function () {
                if (txtName.value == "") {
                    document.getElementById("checkName").innerHTML = "账号不能为空！";
                } else {
                    document.getElementById("checkName").innerHTML = "";
                }
                checkWrite();
            }

            let txtPwd = document.getElementById("txtPwd");
            txtPwd.onblur = function () {
                if (txtPwd.value == "") {
                    document.getElementById("checkPwd").innerHTML = "密码不能为空！";
                } else {
                    document.getElementById("checkPwd").innerHTML = "";
                }
                checkWrite();
            }

            let txtCode = document.getElementById("txtCode");
            txtCode.onblur = function () {
                if (txtCode.value == "") {
                    document.getElementById("checkCode").innerHTML = "验证码不能为空！";
                } else {
                    $.ajax({
                        url: "/Login/CheckCode",
                        type: "post",
                        data: { "txtCode": txtCode.value },
                        success: function (data) {
                            if (data == "ok") {
                                document.getElementById("checkCode").innerHTML = "";
                            } else {
                                document.getElementById("checkCode").innerHTML = "验证码输入错误！";
                            }
                        }
                    });
                }
                checkWrite();
            }

        }

        function checkWrite() {
            if (txtName.value != "" && txtPwd.value != "" && txtCode.value != "") {
                document.getElementById("btnLogin").style.display = "block";
            } else {
                document.getElementById("btnLogin").style.display = "none";
            }
        }

        function changeCheckCode() {
            document.getElementById("vCode").src = "/Login/ShowValidateCode?d="+new Date().getMilliseconds();
        }

        function afterLogin(data) {
            var serverData = data.split(':');
            if (serverData[0]=="ok") {
                window.location.href = "/Home/Index";
            } else if (serverData[0] == "no") {
                alert("查无此人");
                txtName.value = "";
                txtPwd.value = "";
                txtCode.value = "";
            } else if (serverData[0] == "null") {
                document.getElementById("checkCode").innerHTML = "验证码错误！";
            }
        }
    </script>
</head>
<body>
    <div>
        <center>
            @using (Ajax.BeginForm("UserLogin", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterLogin" }, new { id = "loginForm" }))
            {
                <table>
                    <tr><th colspan="2"><h3>CMS系统账号登录</h3></th></tr>
                    <tr><td>账号</td><td><input type="text" name="txtName" id="txtName" /></td><td><span id="checkName"></span></td></tr>
                    <tr><td>密码</td><td><input type="password" name="txtPwd" id="txtPwd" /></td><td><span id="checkPwd"></span></td></tr>
                    <tr><td>验证码</td><td><input type="text" name="txtCode" id="txtCode" /></td><td><span id="checkCode"></span></td></tr>
                    <tr><td></td><td><img src="/Login/ShowValidateCode" id="vCode" /><a href="javascript:void(0)" onclick="changeCheckCode()">看不清，换一张</a></td></tr>
                    <tr><td></td><td><input type="submit" value="登录" id="btnLogin" /></td></tr>
                </table>
            }
        </center>
    </div>
</body>
</html>

三层架构+mvc+easyui/CMS.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>